FROM scratch
LABEL org.opencontainers.image.title="peer pods" \
      org.opencontainers.image.description="The peer pods extension" \
      org.opencontainers.image.vendor="spotlesstofu" \
      io.podman-desktop.api.version=">= 0.12.0"
COPY package.json /extension/
COPY icon.png /extension/
COPY dist/ /extension/dist
