FROM scratch
LABEL org.opencontainers.image.title="My first extension" \
      org.opencontainers.image.description="Example of extension" \
      org.opencontainers.image.vendor="podman-desktop" \
      io.podman-desktop.api.version=">= 0.12.0"
COPY package.json /extension/
COPY icon.png /extension/
COPY src/* /extension/dist/
