# Layer on top of the Podman machine image.
FROM quay.io/podman/machine-os:5.1

RUN \
# Install dependencies.
rpm-ostree install cri-o containernetworking-plugins kata-containers && \
# Enable services.
systemctl enable crio && \
systemctl enable podman

# Copy configuration.
COPY kata.toml /opt/kata/configuration-remote.toml
COPY crio.conf /etc/crio/crio.conf.d/50-kata-remote
